### ISSUE TITLE
Odd Even Linked List

### ISSUE THREAD

**Issue by Jeevasimba** [nikoo28/java-solutions#11]
[Question](https://leetcode.com/problems/odd-even-linked-list/description/)

[your answer](https://github.com/nikoo28/java-solutions/blob/master/src/main/java/leetcode/medium/OddEvenLinkedList.java)

I can't understand about how the head returns the value.

![image](https://user-images.githubusercontent.com/96039278/223669041-af0f28b9-319b-41f5-916e-7b0b30014727.png)

Here, odd variable's value is assigned as head. But , how the head returns the answer ? 

For example :
 
![image](https://user-images.githubusercontent.com/96039278/223669216-29d357af-275e-46d3-9dd7-9b4c561d0706.png)

I assigned the value of "a" as 3 and "b" as "a". If I change the value of b. the value of "b" only changes .

But , how you returned the head as answer ?3

could you please answer me ?

**Comment by nikoo28** [comment]
With linked lists, you refer to a memory address and you change the value at that location. This is not what happens with primitive datatypes like `int`, `double` etc. 
Watch my introductory video on linked lists, to understand it better :)

https://youtu.be/lrXpTVEAXCM

**Comment by Jeevasimba** [comment]
I understood. thanks for reply.
