### ISSUE TITLE
add problems of recursion and dynamic programming

### ISSUE THREAD

**Issue by 6736-shafi** [nikoo28/java-solutions#14]
please try to  add problems such as recursion which is back born of data structure and algorithm

**Comment by nikoo28** [comment]
there are multiple problems available that involve recursion and dynamic programming. Also, mostly all recursive problem can be solved by iterative approaches, which are easier to debug and visualize.

Please let me know if you have any specific problems for request. I will close this issue in 1 week.
Awaiting your concerns :)
